### Signup a new user 
POST http://localhost:3000/auth/signup
content-type: application/json

{
    "email": "rolani7@icloud.com",
    "password": "Given@1234"
   
}


### Signin a new user 
POST http://localhost:3000/auth/signin
content-type: application/json

{
    "email": "rolani7@icloud.com",
    "password": "Given@1234"
   
}

### Find a specific user by Id
GET  http://localhost:3000/auth/5

### Find All users with a given email
GET http://localhost:3000/auth?

### Delete a user by specified id
DELETE http://localhost:3000/auth/1

### Update a specific user based on id 
PATCH http://localhost:3000/auth/1
content-type: application/json

{
    "email": "rolani1@icloud.com",
    "password": "12948595"
}